name: Code Review with CodeRabbit

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run CodeRabbit review
      run: |
        curl -L https://coderabbit.ai/api/run-review \
        --header "Authorization: Bearer cr-7bf6531acd73250d533565e76c727636e4aa7d914ca52f8914af8408e5" \
        --data "repository=${{ github.repository }}&commit=${{ github.sha }}"