name: Code Review with CodeRabbit

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run CodeRabbit review
      run: |
        curl -L https://coderabbit.ai/api/run-review \
        --header "Authorization: Bearer cr-7bf6531acd73250d533565e76c727636e4aa7d914ca52f8914af8408e5" \
        --data "repository=${{ github.repository }}&commit=${{ github.sha }}"