name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"

      # Install dependencies
      - run: pnpm install --frozen-lockfile

      # Run tests
      - name: Run tests
        run: pnpm run test

      # Lint and build the project if tests pass
      - run: pnpm run lint && pnpm run build